name: Transformational Storytelling
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85915
title: Spiritual Transformation through the power of Story.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfcbcc'
    - '#9f9fa9'
    - '#020701'
    - '#626166'
    - '#2d322b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
