name: Transformational Storytelling
favicon: null
layout_spectrum: 0.24501
typography_spectrum: 0.58221
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#110c08'
    - '#60281c'
    - '#b25e25'
    - '#6f4e23'
    - '#d23225'
  brandStrength: 0.5901225889101624
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
