typography_spectrum: 0.43651
color:
  brandColors:
    - '#cfcbcc'
    - '#9f9fa9'
    - '#020701'
    - '#626166'
    - '#2d322b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74232
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b6ea1546-1acf-4d2f-bc4e-0dcdd254e330.jpg
name: Transformational Storytelling
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Spiritual Transformation through the power of Story.
purpose: []
